// This file is auto-generated by maintenance/generateCCAPIInterface.ts
// Do not edit it by hand or your changes will be lost!

import type { CommandClasses } from "@zwave-js/core";
import type { CCAPI } from "./API.js";

// Maps CC names to their CommandClasses enum values
export type CCNameMap = {};

// Maps CC names to their API class types
export interface CCAPIs {
	[Symbol.iterator](): Iterator<CCAPI>;
}
