import * as fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const sourceDir = path.join(__dirname, "../src");

//
// Generate PACKAGE_VERSION module
//
const { version: PACKAGE_VERSION } = JSON.parse(
	fs.readFileSync(path.join(__dirname, "../package.json"), "utf8"),
);
const versionFileName = path.join(sourceDir, "_version.ts");
const code = `// This file is auto-generated by the codegen maintenance script
export const PACKAGE_VERSION = "${PACKAGE_VERSION}";
`;
fs.writeFileSync(versionFileName, code, "utf8");
