// This file is auto-generated by maintenance/generateCCAPIInterface.ts
// Do not edit it by hand or your changes will be lost!

import type { CommandClasses } from "@zwave-js/core";
import type { CCAPI } from "./API.js";

// Maps CC names to their CommandClasses enum values
export type CCNameMap = {
	"Alarm Sensor": typeof CommandClasses["Alarm Sensor"];
	"Application Status": typeof CommandClasses["Application Status"];
	"Association Group Information":
		typeof CommandClasses["Association Group Information"];
	"Barrier Operator": typeof CommandClasses["Barrier Operator"];
	"Basic Window Covering": typeof CommandClasses["Basic Window Covering"];
	"Binary Sensor": typeof CommandClasses["Binary Sensor"];
	"Binary Switch": typeof CommandClasses["Binary Switch"];
	"Central Scene": typeof CommandClasses["Central Scene"];
	"Climate Control Schedule":
		typeof CommandClasses["Climate Control Schedule"];
	"Color Switch": typeof CommandClasses["Color Switch"];
	"CRC-16 Encapsulation": typeof CommandClasses["CRC-16 Encapsulation"];
	"Device Reset Locally": typeof CommandClasses["Device Reset Locally"];
	"Door Lock Logging": typeof CommandClasses["Door Lock Logging"];
	"Door Lock": typeof CommandClasses["Door Lock"];
	"Energy Production": typeof CommandClasses["Energy Production"];
	"Entry Control": typeof CommandClasses["Entry Control"];
	"Firmware Update Meta Data":
		typeof CommandClasses["Firmware Update Meta Data"];
	"Humidity Control Mode": typeof CommandClasses["Humidity Control Mode"];
	"Humidity Control Operating State":
		typeof CommandClasses["Humidity Control Operating State"];
	"Humidity Control Setpoint":
		typeof CommandClasses["Humidity Control Setpoint"];
	"Inclusion Controller": typeof CommandClasses["Inclusion Controller"];
	"Manufacturer Proprietary":
		typeof CommandClasses["Manufacturer Proprietary"];
	"Manufacturer Specific": typeof CommandClasses["Manufacturer Specific"];
	"Multi Channel Association":
		typeof CommandClasses["Multi Channel Association"];
	"Multi Channel": typeof CommandClasses["Multi Channel"];
	"Multi Command": typeof CommandClasses["Multi Command"];
	"Multilevel Sensor": typeof CommandClasses["Multilevel Sensor"];
	"Multilevel Switch": typeof CommandClasses["Multilevel Switch"];
	"No Operation": typeof CommandClasses["No Operation"];
	"Node Naming and Location":
		typeof CommandClasses["Node Naming and Location"];
	"Scene Activation": typeof CommandClasses["Scene Activation"];
	"Scene Actuator Configuration":
		typeof CommandClasses["Scene Actuator Configuration"];
	"Scene Controller Configuration":
		typeof CommandClasses["Scene Controller Configuration"];
	"Schedule Entry Lock": typeof CommandClasses["Schedule Entry Lock"];
	"Security 2": typeof CommandClasses["Security 2"];
	"Sound Switch": typeof CommandClasses["Sound Switch"];
	"Thermostat Fan Mode": typeof CommandClasses["Thermostat Fan Mode"];
	"Thermostat Fan State": typeof CommandClasses["Thermostat Fan State"];
	"Thermostat Mode": typeof CommandClasses["Thermostat Mode"];
	"Thermostat Operating State":
		typeof CommandClasses["Thermostat Operating State"];
	"Thermostat Setback": typeof CommandClasses["Thermostat Setback"];
	"Thermostat Setpoint": typeof CommandClasses["Thermostat Setpoint"];
	"Time Parameters": typeof CommandClasses["Time Parameters"];
	"User Code": typeof CommandClasses["User Code"];
	"Wake Up": typeof CommandClasses["Wake Up"];
	"Window Covering": typeof CommandClasses["Window Covering"];
	"Z-Wave Plus Info": typeof CommandClasses["Z-Wave Plus Info"];
	Association: typeof CommandClasses["Association"];
	Basic: typeof CommandClasses["Basic"];
	Battery: typeof CommandClasses["Battery"];
	Clock: typeof CommandClasses["Clock"];
	Configuration: typeof CommandClasses["Configuration"];
	Indicator: typeof CommandClasses["Indicator"];
	Irrigation: typeof CommandClasses["Irrigation"];
	Language: typeof CommandClasses["Language"];
	Lock: typeof CommandClasses["Lock"];
	Meter: typeof CommandClasses["Meter"];
	Notification: typeof CommandClasses["Notification"];
	Powerlevel: typeof CommandClasses["Powerlevel"];
	Protection: typeof CommandClasses["Protection"];
	Security: typeof CommandClasses["Security"];
	Supervision: typeof CommandClasses["Supervision"];
	Time: typeof CommandClasses["Time"];
	Version: typeof CommandClasses["Version"];
};

// Maps CC names to their API class types
export interface CCAPIs {
	[Symbol.iterator](): Iterator<CCAPI>;

	"Alarm Sensor": import("../cc/AlarmSensorCC.js").AlarmSensorCCAPI;
	"Application Status":
		import("../cc/ApplicationStatusCC.js").ApplicationStatusCCAPI;
	"Association Group Information":
		import("../cc/AssociationGroupInfoCC.js").AssociationGroupInfoCCAPI;
	"Barrier Operator":
		import("../cc/BarrierOperatorCC.js").BarrierOperatorCCAPI;
	"Basic Window Covering":
		import("../cc/BasicWindowCoveringCC.js").BasicWindowCoveringCCAPI;
	"Binary Sensor": import("../cc/BinarySensorCC.js").BinarySensorCCAPI;
	"Binary Switch": import("../cc/BinarySwitchCC.js").BinarySwitchCCAPI;
	"Central Scene": import("../cc/CentralSceneCC.js").CentralSceneCCAPI;
	"Climate Control Schedule":
		import("../cc/ClimateControlScheduleCC.js").ClimateControlScheduleCCAPI;
	"Color Switch": import("../cc/ColorSwitchCC.js").ColorSwitchCCAPI;
	"CRC-16 Encapsulation": import("../cc/CRC16CC.js").CRC16CCAPI;
	"Device Reset Locally":
		import("../cc/DeviceResetLocallyCC.js").DeviceResetLocallyCCAPI;
	"Door Lock Logging":
		import("../cc/DoorLockLoggingCC.js").DoorLockLoggingCCAPI;
	"Door Lock": import("../cc/DoorLockCC.js").DoorLockCCAPI;
	"Energy Production":
		import("../cc/EnergyProductionCC.js").EnergyProductionCCAPI;
	"Entry Control": import("../cc/EntryControlCC.js").EntryControlCCAPI;
	"Firmware Update Meta Data":
		import("../cc/FirmwareUpdateMetaDataCC.js").FirmwareUpdateMetaDataCCAPI;
	"Humidity Control Mode":
		import("../cc/HumidityControlModeCC.js").HumidityControlModeCCAPI;
	"Humidity Control Operating State":
		import("../cc/HumidityControlOperatingStateCC.js").HumidityControlOperatingStateCCAPI;
	"Humidity Control Setpoint":
		import("../cc/HumidityControlSetpointCC.js").HumidityControlSetpointCCAPI;
	"Inclusion Controller":
		import("../cc/InclusionControllerCC.js").InclusionControllerCCAPI;
	"Manufacturer Proprietary":
		import("../cc/ManufacturerProprietaryCC.js").ManufacturerProprietaryCCAPI;
	"Manufacturer Specific":
		import("../cc/ManufacturerSpecificCC.js").ManufacturerSpecificCCAPI;
	"Multi Channel Association":
		import("../cc/MultiChannelAssociationCC.js").MultiChannelAssociationCCAPI;
	"Multi Channel": import("../cc/MultiChannelCC.js").MultiChannelCCAPI;
	"Multi Command": import("../cc/MultiCommandCC.js").MultiCommandCCAPI;
	"Multilevel Sensor":
		import("../cc/MultilevelSensorCC.js").MultilevelSensorCCAPI;
	"Multilevel Switch":
		import("../cc/MultilevelSwitchCC.js").MultilevelSwitchCCAPI;
	"No Operation": import("../cc/NoOperationCC.js").NoOperationCCAPI;
	"Node Naming and Location":
		import("../cc/NodeNamingCC.js").NodeNamingAndLocationCCAPI;
	"Scene Activation":
		import("../cc/SceneActivationCC.js").SceneActivationCCAPI;
	"Scene Actuator Configuration":
		import("../cc/SceneActuatorConfigurationCC.js").SceneActuatorConfigurationCCAPI;
	"Scene Controller Configuration":
		import("../cc/SceneControllerConfigurationCC.js").SceneControllerConfigurationCCAPI;
	"Schedule Entry Lock":
		import("../cc/ScheduleEntryLockCC.js").ScheduleEntryLockCCAPI;
	"Security 2": import("../cc/Security2CC.js").Security2CCAPI;
	"Sound Switch": import("../cc/SoundSwitchCC.js").SoundSwitchCCAPI;
	"Thermostat Fan Mode":
		import("../cc/ThermostatFanModeCC.js").ThermostatFanModeCCAPI;
	"Thermostat Fan State":
		import("../cc/ThermostatFanStateCC.js").ThermostatFanStateCCAPI;
	"Thermostat Mode": import("../cc/ThermostatModeCC.js").ThermostatModeCCAPI;
	"Thermostat Operating State":
		import("../cc/ThermostatOperatingStateCC.js").ThermostatOperatingStateCCAPI;
	"Thermostat Setback":
		import("../cc/ThermostatSetbackCC.js").ThermostatSetbackCCAPI;
	"Thermostat Setpoint":
		import("../cc/ThermostatSetpointCC.js").ThermostatSetpointCCAPI;
	"Time Parameters": import("../cc/TimeParametersCC.js").TimeParametersCCAPI;
	"User Code": import("../cc/UserCodeCC.js").UserCodeCCAPI;
	"Wake Up": import("../cc/WakeUpCC.js").WakeUpCCAPI;
	"Window Covering": import("../cc/WindowCoveringCC.js").WindowCoveringCCAPI;
	"Z-Wave Plus Info": import("../cc/ZWavePlusCC.js").ZWavePlusCCAPI;
	Association: import("../cc/AssociationCC.js").AssociationCCAPI;
	Basic: import("../cc/BasicCC.js").BasicCCAPI;
	Battery: import("../cc/BatteryCC.js").BatteryCCAPI;
	Clock: import("../cc/ClockCC.js").ClockCCAPI;
	Configuration: import("../cc/ConfigurationCC.js").ConfigurationCCAPI;
	Indicator: import("../cc/IndicatorCC.js").IndicatorCCAPI;
	Irrigation: import("../cc/IrrigationCC.js").IrrigationCCAPI;
	Language: import("../cc/LanguageCC.js").LanguageCCAPI;
	Lock: import("../cc/LockCC.js").LockCCAPI;
	Meter: import("../cc/MeterCC.js").MeterCCAPI;
	Notification: import("../cc/NotificationCC.js").NotificationCCAPI;
	Powerlevel: import("../cc/PowerlevelCC.js").PowerlevelCCAPI;
	Protection: import("../cc/ProtectionCC.js").ProtectionCCAPI;
	Security: import("../cc/SecurityCC.js").SecurityCCAPI;
	Supervision: import("../cc/SupervisionCC.js").SupervisionCCAPI;
	Time: import("../cc/TimeCC.js").TimeCCAPI;
	Version: import("../cc/VersionCC.js").VersionCCAPI;
}
